/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contarestaurante;

import java.text.DecimalFormat;

/**
 *
 * @author laura
 */
public class DivisaoConta extends javax.swing.JFrame {

    /**
     * Creates new form DivisaoConta
     */
    public DivisaoConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTaxaServico = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblConsTotal = new javax.swing.JLabel();
        lblCouvPessoa = new javax.swing.JLabel();
        txtFConsTotal = new javax.swing.JTextField();
        txtFCouvPessoa = new javax.swing.JTextField();
        lblTaxaServico = new javax.swing.JLabel();
        btnRadioSim = new javax.swing.JRadioButton();
        btnRadioNao = new javax.swing.JRadioButton();
        lblQtPessoas = new javax.swing.JLabel();
        comBoxQtPessoas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblCustoTotal = new javax.swing.JLabel();
        lblValorPessoa = new javax.swing.JLabel();
        txtFCustoTotal = new javax.swing.JTextField();
        txtFValorPessoa = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dividir Conta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Consumo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18))); // NOI18N

        lblConsTotal.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblConsTotal.setText("Consumo Total (R$)");

        lblCouvPessoa.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblCouvPessoa.setText("Couvert por Pessoa (R$)");

        lblTaxaServico.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblTaxaServico.setText("Possui taxa de serviço (10%)?");

        btnGroupTaxaServico.add(btnRadioSim);
        btnRadioSim.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        btnRadioSim.setText("Sim");

        btnGroupTaxaServico.add(btnRadioNao);
        btnRadioNao.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        btnRadioNao.setText("Não");

        lblQtPessoas.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblQtPessoas.setText("Dividir em quantas pessoas?");

        comBoxQtPessoas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        comBoxQtPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxQtPessoasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsTotal)
                            .addComponent(txtFConsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCouvPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFCouvPessoa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTaxaServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRadioSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioNao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQtPessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxQtPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsTotal)
                    .addComponent(lblCouvPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFConsTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtFCouvPessoa))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaServico)
                    .addComponent(btnRadioSim)
                    .addComponent(btnRadioNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtPessoas)
                    .addComponent(comBoxQtPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Custo Final", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18))); // NOI18N
        jPanel2.setEnabled(false);

        lblCustoTotal.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblCustoTotal.setText("Custo Total (R$)");

        lblValorPessoa.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblValorPessoa.setText("Valor por Pessoa (R$)");

        txtFCustoTotal.setEditable(false);
        txtFCustoTotal.setEnabled(false);

        txtFValorPessoa.setEditable(false);
        txtFValorPessoa.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustoTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorPessoa)
                    .addComponent(txtFValorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustoTotal)
                    .addComponent(lblValorPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFCustoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtFValorPessoa))
                .addContainerGap())
        );

        btnCalcular.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        float consumoTotal = Float.parseFloat(txtFConsTotal.getText());
        int couvertPorPessoa = Integer.parseInt(txtFCouvPessoa.getText());
        float taxaDeServico;
        float custoTotal = 0.0f;
        int couvertTotal;
        float valorPorPessoa = 0.0f;
        DecimalFormat formatar = new DecimalFormat("0.00");
        
        if (btnRadioSim.isSelected()) {
            taxaDeServico = (consumoTotal * 0.1f) + consumoTotal;
            custoTotal += taxaDeServico;
        } else {
            custoTotal += consumoTotal;
        }
        
        switch (comBoxQtPessoas.getSelectedIndex()) {
            case 0: 
                custoTotal += couvertPorPessoa;
                valorPorPessoa = custoTotal;
                break;
            case 1:
                couvertTotal = couvertPorPessoa * 2;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/2;
                break;
            case 2:
                couvertTotal = couvertPorPessoa * 3;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/3;
                break;
            case 3: 
                couvertTotal = couvertPorPessoa * 4;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/4;
                break;
            case 4:
                couvertTotal = couvertPorPessoa * 5;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/5;
                break;
            case 5:
                couvertTotal = couvertPorPessoa * 6;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/6;
                break;
            case 6:
                couvertTotal = couvertPorPessoa * 7;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/7;
                break;
            case 7:
                couvertTotal = couvertPorPessoa * 8;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/8;
                break;
            case 8:
                couvertTotal = couvertPorPessoa * 9;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/9;
                break;
            case 9:
                couvertTotal = couvertPorPessoa * 10;
                custoTotal += couvertTotal;
                valorPorPessoa = custoTotal/10;
                break;
        }
        jPanel2.setEnabled(true);
        txtFCustoTotal.setEnabled(true);
        txtFValorPessoa.setEnabled(true);
        txtFCustoTotal.setText(String.valueOf(formatar.format(custoTotal)));
        txtFValorPessoa.setText(String.valueOf(formatar.format(valorPorPessoa)));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtFConsTotal.setText("");
        txtFCouvPessoa.setText("");
        btnGroupTaxaServico.clearSelection();
        comBoxQtPessoas.setSelectedIndex(0);
        txtFCustoTotal.setText("");
        txtFValorPessoa.setText("");
        jPanel2.setEnabled(false);
        txtFCustoTotal.setEnabled(false);
        txtFValorPessoa.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void comBoxQtPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxQtPessoasActionPerformed
        btnCalcular.setEnabled(true);
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_comBoxQtPessoasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DivisaoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DivisaoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DivisaoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DivisaoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DivisaoConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup btnGroupTaxaServico;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton btnRadioNao;
    private javax.swing.JRadioButton btnRadioSim;
    private javax.swing.JComboBox<String> comBoxQtPessoas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConsTotal;
    private javax.swing.JLabel lblCouvPessoa;
    private javax.swing.JLabel lblCustoTotal;
    private javax.swing.JLabel lblQtPessoas;
    private javax.swing.JLabel lblTaxaServico;
    private javax.swing.JLabel lblValorPessoa;
    private javax.swing.JTextField txtFConsTotal;
    private javax.swing.JTextField txtFCouvPessoa;
    private javax.swing.JTextField txtFCustoTotal;
    private javax.swing.JTextField txtFValorPessoa;
    // End of variables declaration//GEN-END:variables
}
